version: '3'
services:
  api:
    container_name: flask-container
    build: .
    entrypoint: python app.py
    env_file:
      - .env
    ports:
      - '5000:5000'
  worker:
    build: .
    command: python worker.py
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    depends_on:
      - api
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
  